### PR TITLE
Bump kyverno to 1.7.5

### PR DESCRIPTION
**Pull request by sudo-bmitch**
Signed-off-by: Brandon Mitchell <git@bmitch.net>

Bumps Kyverno due to a breaking change in cosign: https://github.com/kyverno/kyverno/releases/tag/v1.7.5

1.8.1 was not used due to multiple breaking issues with that release.

### CODE REVIEW

**Review by developer-guy — APPROVED** [review]
Lgtm again ☝️

**Comment by developer-guy** [comment]
as It seems fixed https://github.com/kyverno/kyverno/issues/5163, should we go back to 1.8.1, which is the most recent version of kyverno?

**Comment by sudo-bmitch** [comment]
> as It seems fixed https://github.com/kyverno/kyverno/issues/5163, should we go back to 1.8.1, which is the most recent version of kyverno? 

The other issue I encountered was annotations getting too large to use `kubectl apply`, only `create` and `replace` would work.

**Review by bradbeck — APPROVED** [review]

**Review by mlieberman85 — APPROVED** [review]
LGTM

**Comment by developer-guy** [comment]
> > as It seems fixed [kyverno/kyverno#5163](https://github.com/kyverno/kyverno/issues/5163), should we go back to 1.8.1, which is the most recent version of kyverno?
> 
> The other issue I encountered was annotations getting too large to use `kubectl apply`, only `create` and `replace` would work.

Do you have comments folx ? ☝️ @chipzoller @eddycharly

**Pull request merged**
