### PR TITLE
Update Cue v0.8.0 -> v0.9.0

### PR DESCRIPTION
**Pull request by bradbeck**
Release: https://github.com/cue-lang/cue/releases/tag/v0.9.0

### CODE REVIEW

**Review by rgreinho — DISMISSED** [review]
👍

**Review by sudo-bmitch — APPROVED** [review]
LGTM

**Review by sudo-bmitch — CHANGES_REQUESTED** [review]
Actually I take that back, CI failed on this one.

**Comment by bradbeck** [comment]
> Actually I take that back, CI failed on this one.

Looks like `cue mod fix` should patch things up.

**Review by rgreinho — APPROVED** [review]

**Review by sudo-bmitch — APPROVED** [review]

**Pull request merged**
