### PR TITLE
Update buildType in ClusterPolicy

### PR DESCRIPTION
**Pull request by bradbeck**
Recent versions of Chains are now using `tekton.dev/v1beta1/TaskRun` instead of `https://tekton.dev/attestations/chains@v2` as the `buildType` in the SLSA attestation.

This PR updates the Kyverno `ClusterPolicy` for the public repository where built images are pushed.

Fixes: https://github.com/buildsec/frsca/issues/372

Signed-off-by: Brad Beck <bradley.beck@gmail.com>

### CODE REVIEW

**Comment by bradbeck** [comment]
https://github.com/tektoncd/chains/pull/601 appears to be the source of the change to `buildType`

**Review by pxp928 — APPROVED** [review]
LGTM

**Comment by bradbeck** [comment]
Fixes: https://github.com/buildsec/frsca/issues/372

**Review by mlieberman85 — APPROVED** [review]
LGTM

**Pull request merged**
