### PR TITLE
Drop Tekton Dashboard

### PR DESCRIPTION
**Pull request by bradbeck**
Signed-off-by: Brad Beck <bradley.beck@gmail.com>

### CODE REVIEW

**Review by sudo-bmitch — APPROVED** [review]
LGTM

**Comment by rgreinho** [comment]
Out of curiosity, why do we want to drop the dashboard?

**Comment by bradbeck** [comment]
The dashboard does not provide any core functionality to FRSCA and @pxp928 had mentioned that we could remove it.

**Review by pxp928 — APPROVED** [review]
LGTM

**Pull request merged**
