### PR TITLE
Use internal registry with kyverno

### PR DESCRIPTION
**Pull request by sudo-bmitch**
This follows #436. It changes the registry from 127.0.0.1 or registry.registry to the minikube internal name which can also be used by both admission controllers running in a pod and the k8s node pulling the images. This does require the registry-proxy to be running in the background.

Because of #430, the attestation admission control policy is set to `validationFailureAction: "Audit"`.

### CODE REVIEW

**Comment by bradbeck** [comment]
I'm not able to reliably run minikube on my M1 Mac at the moment, so I can't really verify this change.

**Comment by bradbeck** [comment]
I was able to validate the changes by using `minikube` running on top of `colima`.

I did have to `export REGISTRY_PORT=5500` because `5000` is in use by a MacOS related service.

**Comment by bradbeck** [comment]
😄 Looks like I just needed to delete the `minikube` volume in Docker Desktop in order to make minikube happy again.

Also still needed to `export REGISTRY_PORT=5500` since ControlCenter (AirPlay) is using `5000`.

**Review by bradbeck — APPROVED** [review]

**Comment by sudo-bmitch** [comment]
Force push was just a rebase.

**Pull request closed without merging**
