### PR TITLE
Documenting the FRSCA architecture

### PR DESCRIPTION
**Pull request by sudo-bmitch**
This documents the architecture of FRSCA to hopefully answer some of the questions of how signing happens, and how Vault, Spire, and admission controllers are integrated.

### CODE REVIEW

**Comment by jondkent** [comment]
Are Github triggers in place today?

**Comment by sudo-bmitch** [comment]
> Are Github triggers in place today?

Are you looking for a doc site preview? Or just seeing the CI succeed?

**Comment by jondkent** [comment]
> > Are Github triggers in place today?
> 
> Are you looking for a doc site preview? Or just seeing the CI succeed?
Hi, nope just wondering if Github triggers has been setup as I don't see anything in Frsca and is its documented like it exists.  Could always have missed it.

**Comment by sudo-bmitch** [comment]
> Hi, nope just wondering if Github triggers has been setup as I don't see anything in Frsca and is its documented like it exists.  Could always have missed it.

Oh, the Git triggers into Tekton, I thought you were asking about the GitHub actions here. Those triggers are a bit forward looking right now, as is the admission controller policies. There's a lot still left to develop.

**Review by rgreinho — APPROVED** [review]
👍

**Review by jondkent — APPROVED** [review]
lgtm

**Comment by pxp928** [comment]
@sudo-bmitch I know that it currently doesn't exist but there would be a connection with spire + pipelines also.

**Comment by pxp928** [comment]
Based on the diagram I looks like spire server and vault are outside in a trusted k8s cluster. Which is great. But why is run-time visibility there also? Maybe I am understanding the diagram wrong.

**Comment by sudo-bmitch** [comment]
@pxp928 

> I know that it currently doesn't exist but there would be a connection with spire + pipelines also.

Ok, I can flip some things around to make that easier to draw.

> Based on the diagram I looks like spire server and vault are outside in a trusted k8s cluster. Which is great. But why is run-time visibility there also? Maybe I am understanding the diagram wrong.

I was aiming for trust boundaries, but there's a good chance that needs to be moved to be along side the admission controller. The part I want to be sure of is if an attacker does something in a task that manages to escape, runtime visibility should both detect that, and not be able to be disabled by that malicious code without some kind of detection.

**Pull request merged**
