### PR TITLE
Add Testinfra project

### PR DESCRIPTION
**Pull request by rgreinho**
Adds a Python project to run integration tests using the Testinfra
framework.

### CODE REVIEW

**Review by pxp928 — APPROVED** [review]
Very nice! LGTM and easy to add more tests.

**Review by 06kellyjac — APPROVED** [review]
LGTM

**Review by sudo-bmitch — CHANGES_REQUESTED** [review]
There's some discussion on this in slack. Let's leave this open until we have some consensus.

**Comment by rgreinho** [comment]
The decision was to postpone this to when we will actually need more tests. In its current state, the project already has a good amount of validations and integration testing.

We could re-open this issue when needed.

**Pull request closed without merging**
