### PR TITLE
Temporarily switch to sha256 for vendor validation

### PR DESCRIPTION
**Pull request by bradbeck**
Switch to sha256 validation temporarily while vendorme is being updated to handle recent Rekor changes.

Signed-off-by: Brad Beck <bradley.beck@gmail.com>

### CODE REVIEW

**Review by sudo-bmitch — APPROVED** [review]
LGTM

**Comment by JonZeolla** [comment]
Before merging we should make sure there's an issue on the backlog for the long term fix and reference it here

**Comment by bradbeck** [comment]
> Before merging we should make sure there's an issue on the backlog for the long term fix and reference it here

https://github.com/trmiller/vendorme/issues/4

**Review by pxp928 — APPROVED** [review]
LGTM

**Pull request merged**
